spring.application.name=login-mod
# Configuração do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/user_man_database
spring.datasource.username=postgres
spring.datasource.password=postgresadmin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (Hibernate) - Atualiza automaticamente as tabelas
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs

# Security keys config
jwt.private.key=classpath:private_key.pem
jwt.public.key=classpath:public_key.pem
logging.level.org.springframework.security=DEBUG